# Generated by Django 6.0.7 on 2026-08-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('prompt', models.TextField(blank=True)),
                ('overall_score', models.IntegerField(default=0)),
                ('prompt_alignment_score', models.IntegerField(default=0)),
                ('knowledge_validation_score', models.IntegerField(default=0)),
                ('seo_score', models.IntegerField(default=0)),
                ('search_quality_score', models.IntegerField(default=0)),
                ('technical_html_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
